### ISSUE TITLE
遇到千行的json解析时会遇到异常

### ISSUE THREAD

**Issue by aleimu** [zyqwst/json-schema-editor-vue3#10]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'properties')
    at Proxy.render (main.vue:3:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5580:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:1)
    at instance.update (runtime-core.esm-bundler.js:5694:1)
    at setupRenderEffect (runtime-core.esm-bundler.js:5708:1)
    at mountComponent (runtime-core.esm-bundler.js:5490:1)
    at processComponent (runtime-core.esm-bundler.js:5448:1)
    at patch (runtime-core.esm-bundler.js:5038:1)
    at mountChildren (runtime-core.esm-bundler.js:5234:1)
我看demo页面跑没问题,那个应该时vue2版本的吧,vue3版本的在导入千行以上的复杂json时会报错如上,    
左边的json已经显示出来了,但可能不完整然后构建节点时就出错了,还有就是组件多了后太卡了,一次性渲染出来前页面也空白很久,希望能修复一下

**Comment by aleimu** [comment]
排查了一下,时遇到这一串json导致的
{
          "enable_flexible_collision_margin": true,
          "estimator_param": [
            [
              1,
              0,
              0,
              0,
              1
            ]
            ],
          "default_expand": 0
  }
